### ISSUE TITLE
Onkohan tarkoituksella vai jäänyt kaavatietomalli tähän kohtaan?

### ISSUE THREAD

**Issue by teempek** [ilkkarinne/rakentamisenluvat#1]
@ilkkarinne kts. kuva?
<img width="538" alt="image" src="https://user-images.githubusercontent.com/86219971/185548943-ffe200fa-96c4-4ef9-97a8-6a880523bc03.png">

**Comment by ilkkarinne** [comment]
Kappas, joo. Virhehän tuo on. Itse asiassa koko ```title```-kentän voi tuolta poistaa, sillä sivujen selainikkunoissa käytettävät titlet luodaan modulin navigaatiorakenteen perusteella.

**Comment by ilkkarinne** [comment]
Korjattu pull requestissa #27
